### ISSUE TITLE
export_db.py expects token. Does not handle password. 

### ISSUE THREAD

**Issue by johanrex** [databrickslabs/migrate#100]
You can configure databricks-cli to use username and password. In that case there is no token. The file export_db.py does not handle this scenario. 

You configure databricks-cli with password when you issue this command:

    databricks configure

Then the config file looks like this:

```
[DEFAULT]
host = <workspace-URL>
username = <username>
password = <password>
```

See this documentation under "Set up authentication":
https://docs.databricks.com/dev-tools/cli/index.html

**Comment by mrchristine** [comment]
Thanks for pointing this out. We will only support tokens for this tool and I'll update the README to indicate so.
