### ISSUE TITLE
Failure in metastore import for tables with varchar columns

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/migrate#104]
**Description:**

Failure in import of tables created using 'varchar' datatype for columns.

After successful export of Metastore of all the databases and tables. We encountered the following error during the import of a few tables:

![Metastore Error](https://user-images.githubusercontent.com/49161779/152555801-b2888cc1-85b9-4ac5-a5e2-51b451713c81.jpg)

While the rest of the tables got imported successfully without any issues.
All the tables that were not imported were created by passing varchar as datatype for their columns.

**For example:**

![Sample Table](https://user-images.githubusercontent.com/49161779/152532341-2600fb74-3f29-432c-9f97-59ce42b04d1a.jpg)

Is it possible that the tables created using varchar datatype are currently not supported for migration?

**Comment by YatharthKaushik** [comment]
Hey,

Yes we are able to query all these tables in the source workspace and they are working fine.

**Comment by mrchristine** [comment]
There's a mismatch with what's being reported. The error is indicating that your Delta tables have mismatched schemas. I might be working in the source, but the error is telling you that there's a clear mismatch between schemas. Address the error as this isn't a tooling issue with this project.
