### ISSUE TITLE
Error in code during import of some notebooks

### ISSUE THREAD

**Issue by YatharthKaushik** [databrickslabs/migrate#117]
During the migration of notebooks, we are able to successfully export all the notebooks but during the import when we run:
` python import_db.py --profile newWS --workspace --azure`

Some of the notebooks got imported but then we encountered the following error:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/49161779/155287924-b5c62f1e-6a0f-459a-a42c-a4d92f732df6.png">

Could you help us with what might be causing this?

**Comment by kevinkim9264** [comment]
@YatharthKaushik it seems like you are running older version of workspace migration script. Can you try pulling from the latest master and try again?

**Comment by YatharthKaushik** [comment]
Hey, I did that but now I when I try to migrate jobs I get this error:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/49161779/155477621-ca3af294-a892-461f-a8cd-b2f3c415bafc.png">

Could you help me with this?

**Comment by kevinkim9264** [comment]
@YatharthKaushik yeah, as the README.md says, could you run
`python3 setup.py install`? 
or 
`python setup.py install`

**Comment by YatharthKaushik** [comment]
Hey @kevinkim9264,
I tried that and the error got resolved. Thanks!
