### ISSUE TITLE
Failure to import all notebooks due to parallel import silently ignoring http 429 returned from Databricks API

### ISSUE THREAD

**Issue by paulg-mscience** [databrickslabs/migrate#126]
Full import of all notebooks with `--num-parallel 20` overwhelms the Databricks API. Currently the code is silently ignoring http 429 that is being returned from Databricsk API when we post the notebook to the new workspace.

We should retry http 429 with appropriate backoff sleep logic.

Some observations below.

In dbclient.py, when status_code is http 429 then `raw_results.json()` throws exception because raw_results is empty.

```
            http_status_code = raw_results.status_code
            if http_status_code in dbclient.http_error_codes:
                raise Exception("Error: {0} request failed with code {1}\n{2}".format(http_type,
                                                                                      http_status_code,
                                                                                      raw_results.text))
            results = raw_results.json()
```
In WorkspaceClient.py, the child thread throws an exception when executing `resp_upload = self.post(WS_IMPORT, nb_input_args)` and that exception is not being propagated to parent thread.

**Comment by mrchristine** [comment]
@souravkhandelwal09 @kevinkim9264 can we take a look at this, possibly set upper limits on import cases?

**Comment by paulg-mscience** [comment]
I have also experienced http 429 from the databricks API when importing jobs. Jobs import is currently not using the `--num-parallel` feature so this happens with single threaded as well.

Maybe something like this for interaction with the databricks API?
```
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry

retry_strategy = Retry(
    total=10,
    status_forcelist=[429, 500, 502, 503, 504],
)
adapter = HTTPAdapter(max_retries=retry_strategy)
```

**Comment by paulg-mscience** [comment]
@kevinkim9264 What are your initial thoughts on this?

**Comment by kevinkim9264** [comment]
Yeah, setting a limit is really tricky because it just depends on the other usages/traffic of the workspace, the workspace tier, etc. Exponential backoff may help, but it will still lead to the state where the backoff time will be just so long that it will be bad customer experience. Why don't we just `429` as part of `http_error_codes` so that 429 is also caught and thrown? That way, the user can realize that the problem comes from the rate limiting and can make adjust the number of parallelism. 

My take is:
1. Also throw on `429` error code. 
2. Do more proper checkpointing so that retrying is also idempotent e.g. https://github.com/databrickslabs/migrate/issues/125

**Comment by paulg-mscience** [comment]
I think this code in WorkspaceClient.py for importing users in parallel is not going to propagate the exception thrown by the 429. (see https://stackoverflow.com/questions/49322477/concurrent-futures-threadpoolexecutor-swallowing-exceptions-python-3-6)
```
 with ThreadPoolExecutor(max_workers=num_parallel) as executor:
     futures = [executor.submit(_file_upload_helper, file) for file in files]
     concurrent.futures.wait(futures)
```
Also, as stated in an earlier comment, even the job import which is single threaded experiences a 429 every time I import our 1250 jobs. For this reason I feel strongly that retry with backoff on 429 is appropriate. I will make a branch and experiment.

**Comment by kevinkim9264** [comment]
@paulg-mscience you are right. it doesn't have the proper error raise handling and like you said it seems to just swallow the error raise. We should fix it.

**Comment by kevinkim9264** [comment]
@paulg-mscience after some thoughts, I think the invoker of the script should just rely on checkpointer and retry whenever he/she runs into transient issues (networking issues, rate limiting issues) instead of exponential backoff retry. Once we have to checkpointer implemented, the users can idempotently retry whenever transient issues happen.

**Comment by kevinkim9264** [comment]
@paulg-mscience another thought is that if a user uses the pipeline, it lets the particular task finish even if there are errors, but raise error and not proceed to the next stage: https://github.com/databrickslabs/migrate/blob/master/pipeline/pipeline.py#L80 (as long as the task correctly logs the error using the error_logger).

Were you using the pipeline or using the individual step? Could you tell me what command you were using when hitting rate limiting?

**Comment by paulg-mscience** [comment]
> @paulg-mscience after some thoughts, I think the invoker of the script should just rely on checkpointer and retry whenever he/she runs into transient issues (networking issues, rate limiting issues) instead of exponential backoff retry. Once we have to checkpointer implemented, the users can idempotently retry whenever transient issues happen.

@kevinkim9264 This could work for a small workspace but we have 90K notebooks that we need to migrate. When I run import with my experimental retry logic and num-parallel = 8 the notebook import encounters 5502 http 429 failures that are successfully retried. Restarting the import after each failure is not practical in our case. I will have a PR for review soon when I finish my local testing. You can then decide if you want to merge the retry logic.

**Comment by paulg-mscience** [comment]
> @paulg-mscience another thought is that if a user uses the pipeline, it lets the particular task finish even if there are errors, but raise error and not proceed to the next stage: https://github.com/databrickslabs/migrate/blob/master/pipeline/pipeline.py#L80 (as long as the task correctly logs the error using the error_logger).
> 
> Were you using the pipeline or using the individual step? Could you tell me what command you were using when hitting rate limiting?

@kevinkim9264 We are using the pipeline, but in our fork we have commented out line https://github.com/databrickslabs/migrate/blob/master/pipeline/pipeline.py#L80 so that the pipeline runs to completion even when errors are encountered. 

Here is the command that I am using when encountering rate limiting:
```
date; time python migration_pipeline.py --profile scratch-blue --import-pipeline --session M20220307222552 --archive-missing --use-checkpoint --num-parallel 8 --retry-total=20 --retry-backoff=1.0 --notebook-format SOURCE --overwrite-notebooks --skip-tasks 'metastore' 'metastore_table_acls' 2>&1 | tee tmp.txt
```

**Comment by paulg-mscience** [comment]
@kevinkim9264 The `5502 http 429 failures` was with `--retry-total=10` and `--retry-backoff=1.0`. I don't have the stats for how many 429s came for first attempt or for retry attempts.

**Comment by paulg-mscience** [comment]
@kevinkim9264 Here is my PR with http retry logic ... https://github.com/databrickslabs/migrate/pull/137

**Comment by paulg-mscience** [comment]
Closed with this PR https://github.com/databrickslabs/migrate/pull/142
