### ISSUE TITLE
remove_automated_clusters regex not removing automated clusters from the new job orchestration

### ISSUE THREAD

**Issue by marcoshm01** [databrickslabs/migrate#133]
With the new job orchestration enhancement, you can now edit automated clusters name. Also the default name for automated clusters does not match the regex inside remove_automated_clusters method:

`re.compile("job-\d+-run-\d+$")`

didn't match the one cluster of mine:
job-68976231-run-202642813-jb_abc

**Comment by mrchristine** [comment]
Apologize for the delay on this. Thanks for pointing this out, yes the new multi-task-jobs allow the tasks to define a name suffix for clusters to identify the job clusters by name. 

I'll work on a patch for this shortly.
