### ISSUE TITLE
Import ACL duplicating permissions

### ISSUE THREAD

**Issue by db-caioishizaka** [databrickslabs/migrate#143]
On the import acl script, it is also patching permissions that are inherited, creating a weird behaviour as below (on source workspace, user had inherited permission to a notebook)

`{
            "user_name": "xxx@xxx.com",
            "all_permissions": [
                {
                    "permission_level": "CAN_READ",
                    "inherited": false
                },
                {
                    "permission_level": "CAN_READ",
                    "inherited": true,
                    "inherited_from_object": [
                        "/directories/1232135443521"
                    ]
                }
            ]
        }`
Though this not cause any permission errors, it is a bit weird that the same user have both inherited and non-inherited permissions.
Also, I believe that eliminating the replication of inherited permissions may speed up the process a lot for workspaces that have very few non-inherited permissions (relies more on directory permissions)

**Comment by kevinkim9264** [comment]
This should've been fixed. thanks
