### ISSUE TITLE
Add ability to run the pipeline in non-interactive mode

### ISSUE THREAD

**Issue by petrcv-db** [databrickslabs/migrate#158]
When importing, I need to answer the question whether I really want to import the workspace.

As I'm calling the migration_pipeline module in a shell script, I had to do something like:
```
 yes | python3 migrate/migration_pipeline.py  --import-pipeline  ...
```
Instead of this, I'd like to have an option to tell the module not to ask any questions.

**Comment by kevinkim9264** [comment]
@petrcv-db This is just one time answering you have to enter, and it is a safety feature to make sure the caller understands what data is being imported into the destination workspace. While the export phase is relatively safe, the import phase can be very sensitive (imagine accidentally importing data into wrong destination workspace).

Also could you explain why having to enter yes one time is a big slow-down problem?

Thank you!

**Comment by gregwood-db** [comment]
Addressed in https://github.com/databrickslabs/migrate/commit/93c64709f1680b4919485f7cb612e88223c2f834 via the --no-prompt input flag when running --import pipeline.
