### ISSUE TITLE
Issue while exporting Hive Metastore

### ISSUE THREAD

**Issue by harshfadiya** [databrickslabs/migrate#174]
While I'm exporting Hive Metastore, I'm getting below errors.

INFO;Logging failure 
ERROR;java.util.concurrent.**ExecutionException**: java.nio.file.AccessDeniedException
ERROR;<span class="ansi-red-fg">**AnalysisException**</span>: dbfs:/mnt/DMA doesn&#39;t exist;

I want suggestion to figur-out, what are possible workarounds.
Thanks in adv.

**Comment by mrchristine** [comment]
Your error indicates you don't have proper roles to access the mounted path `dbfs:/mnt/DMA` It's up to you as an admin to know what type of access is needed for the tables in your metastore. You need to use a cluster with the proper credentials. 

See https://github.com/databrickslabs/migrate#hive-metastore for more details.
