### ISSUE TITLE
 Instance profiles assignment to Cluster

### ISSUE THREAD

**Issue by harshfadiya** [databrickslabs/migrate#175]
I'm working on exporting Hive metastore from workspace. I'm getting error related to AccessDenied while exporting Database tables.

I want to know below :
1. Is there any way we can assign multiple instance profile roles to a single cluster ? 
2. Can we assign multiple roles to single instance profile ?

If I get any suggestion related to these, that'll be helpful.
Thanks in Adv!

**Comment by mrchristine** [comment]
1. No, that's not how AWS instance profiles work. You can assign single profile to a cluster. 
2. No, you cannot. You can define an admin profile that can read all your buckets and use that to migrate.
