### ISSUE TITLE
How can I make an admin instance profile 

### ISSUE THREAD

**Issue by Debanjoy** [databrickslabs/migrate#177]
Hey there,
I was working in one of the migration project where in I have almost 27 different instance profiles and 90 databases. Now the problem is all these Instance profiles are mapped to various databases. So I am not able to migrate the complete hive metastore at one go. Everytime I am required to change the arm in the aws cluster so as to export or import a hivemetastore database. Is there someway I can get all the instance profile mapped to one single instance profile and use it in my cluster so as to migrate the complete metastore at one go else few tables gets left out in the process.

**Comment by mrchristine** [comment]
The best recommendation is to create a master IAM role that can access all the buckets you need and export and import with that master role.
