### ISSUE TITLE
S3 bucket mount and DBFS Migration

### ISSUE THREAD

**Issue by harshfadiya** [databrickslabs/migrate#178]
Hi, As I am performing Databricks workspace migration, I need suggestions on below Query.

(**Note**: Both Databricks workspaces are located on different AWS account consoles)

1. Can you pls suggest best ways to mount S3 buckets from one Databricks account to another ? 
2. Also, best way to perform DBFS migration across different AWS account Databricks workspaces.

Thanks.

**Comment by mrchristine** [comment]
1. You can export the mounts and bucket locations, but we do not support exporting keys that were used to mount them. You'll need to decide if they were mounted using keys or IAM roles. This is up to the design your team has chosen. Use the `--mounts` export to get a list. 
2. You can update all the object ACLs in the source DBFS bucket, then do an `s3sync` between the 2 buckets. Or you can design your DBFS data to use external buckets so you don't need to migrate in the future. 

If you're a paying customer with a support contract, you can reach out to us to assist with further questions.
