### ISSUE TITLE
metastore cmd throwing Err on Missing Database Attributes Log

### ISSUE THREAD

**Issue by Srinidhi1994** [databrickslabs/migrate#179]
After a successful export and while importing I'm getting the following error 

File "/Users/srinidhidaripally/migrate/dbclient/HiveClient.py", line 374, in import_hive_metastore
    raise ValueError('Missing Database Attributes Log. Re-run metastore export')
ValueError: Missing Database Attributes Log. Re-run metastore export

any reason why?

**Comment by mrchristine** [comment]
No, there's not enough info to know why. I'd suggest you pull the latest version, and re-run your export.
