### ISSUE TITLE
import of the meta store is throwing 'InvalidMountException: Could not find correct credentials' after mounting unmanaged table locations

### ISSUE THREAD

**Issue by Srinidhi1994** [databrickslabs/migrate#180]
I have mount unmanaged table locations first in the destination and then used metastore cmds to export and import tables. But while importing it is throwing ERROR;com.databricks.backend.daemon.data.common.InvalidMountException: Could not find correct credentials for /mnt/... path 

But when I hook workspace_migration cluster with the appropriate IAM role for the data, it is able to migrate properly. 
This could be an enhancement

**Comment by mrchristine** [comment]
This is clearly documented and no enhancement needed.
