### ISSUE TITLE
Issue while Importing multiple instance profiles

### ISSUE THREAD

**Issue by harshfadiya** [databrickslabs/migrate#187]
Hi, As I am performing Databricks workspace migration on AWS, I need suggestions on below Query.

While importing instance profiles, I am getting below error and it skip the all new instance profiles-
ERROR : {"Verification of the instance profile failed. AWS error: You are not authorized to perform this operation. Encoded authorization failure message", "http_status_code": 400}

I need suggestions on, how can I skip the validation of instance profiles while Import process, that'll be helpful.

Thanks.

**Comment by mrchristine** [comment]
You cannot skip, you need the instance profiles to exist in the destination location prior to importing other artifacts.

**Comment by harshfadiya** [comment]
Thanks for your response. I understand that instance profiles must exist prior to import of other components.
Actually during Import of instance profiles, due to **instance profile validation**, it is skipping all new instance profiles.
(Note: I can see total 27 instance profiles in the legacy workspace.)

I am looking for any approach, through which I can skip the **validation part** of the instance profiles while import. In other terms, during import, it should bypaas the validation of new instance profiles and directly add in the target workspace. Thanks.

**Comment by mrchristine** [comment]
No, skipping validation is not the correct direction. The validation is there to verify that the destination workspace is configured correctly. We're not going to implement a skip option to bypass a validation.
