### ISSUE TITLE
Job pause_status is not migrated

### ISSUE THREAD

**Issue by sergiu-databricks** [databrickslabs/migrate#196]
Currently there is no functionality to migrate the `pause_status` of a job. During a regular migration, all jobs are migrated with their schedule, but are set up as PAUSED. This is good, as you do not want to have the same job running in two different environments at the same time.

Afterwards, there is functionality to bulk pause/unpause all jobs, but this does what it says on the tin: apply the change to all jobs, regardless of the initial status. So if there is a mixture of paused and unpaused jobs in the original workspace, there is no current way of migrating that. This is bad.

It is worth noting that the original pause_status is stored in `jobs.log`.

**Comment by sergiu-databricks** [comment]
One likely cause of this is that we do not save the mapping between job ids. This [PR](https://github.com/databrickslabs/migrate/pull/195) should solve this though, allowing for this functionality to be implemented.

**Comment by gregwood-db** [comment]
Merged in #197
