### ISSUE TITLE
Azure Service Principal not covered in the migration tool

### ISSUE THREAD

**Issue by hwang-db** [databrickslabs/migrate#216]
Service Principals as workspace users are not covered during user/group export stage, for production workloads, SPNs are crucial for production workloads. If we directly run the migration tool with all steps, it's very prone to errors like SPNs not found and pipeline broke, as other steps like job ACL migration still captures SPNs id into the exported log files.

Makeshift solution could be we skip-task on the whole user migration step, and use a patching script to complete the migration / workspace sync.

**Comment by mrchristine** [comment]
@hwang-db can you work on a fork, create a new branch, test / integrate that work into this project? 
It would be great for you to contribute instead of having a patch / separate script.

**Comment by gregwood-db** [comment]
I started looking at adding SPs to the pipeline- it's pretty simple and would just be an additional step in the export/import. If you're able to pitch in @hwang-db feel free to create a PR and I'll review it.

**Comment by gregwood-db** [comment]
Solved via #222
