### ISSUE TITLE
import Repos fails if the parent dir does not exist

### ISSUE THREAD

**Issue by lorenzorubi-db** [databrickslabs/migrate#219]
e.g. if the tool tries to add a Repo on the target workspace such as
```
/Repos/lorenzo.rubio@databricks.com/migrate
```
the tool will fail if the parent directory does not exist (meaning that the user has never entered into the workspace)

for some customers there is a number of repos in such situation and would be a bit cumbersome to either create each all the folders
(asking the users to login could be out of the question since the migration is not finished yet)

**Comment by gregwood-db** [comment]
Merged #220 to solve this
