### ISSUE TITLE
Spark config on Table ACLs Cluster could impact Hive Metastore version

### ISSUE THREAD

**Issue by veenaramesh** [databrickslabs/migrate#242]
Hi everyone, 

There is a spark config set on the cluster spun up during the export of Table ACLs that could impact the version of the overall Hive Metastore during the export. Specifically: 
`"spark.sql.hive.metastore.version": "1.2.1`

Is there a reason that this config has been added to the cluster?

**Comment by mrchristine** [comment]
There's specific scenarios where long term parquet users might hive a bug where a newer hive client is needed. By fixing the version of the client to 1.2.1 it allows us to cover all use cases for parquet files. If you're only using delta or csv, json, text based files then it is safe to remove.
