### ISSUE TITLE
Error while exporting notebooks

### ISSUE THREAD

**Issue by nunogabrielmonteiro** [databrickslabs/migrate#247]
Hi, we are having an error while exporting notebooks:

ERROR;{"error_code": "BAD_REQUEST", "message": "Size exceeds 10485760 bytes", "http_status_code": 400, "path": "/app/Workloads work/NOTEBOOK"}

Notebooks with more than 10 Mbytes are not supported?

Thank you

**Comment by lsprangers** [comment]
Same issue - the notebooks that are failing are the ones that display a lot of text as well...

Is there a way to skip notebooks that are > 10Mb instead of having to skip all notebooks?

**Comment by gregwood-db** [comment]
I'll close this since it's a platform limit, rather than a limit of this tool. If you think it's valuable to allow skipping of too-large notebooks, open a PR or enhancement request and we can get that added.
