### ISSUE TITLE
Unexpected keyword argument 'allowed_methods' trying to run an export

### ISSUE THREAD

**Issue by TylrRssll** [databrickslabs/migrate#249]
I am attempting to run an export from an azure databricks workspace using the following command from an azure VM running Ubuntu 20.04.

The VM was only launched this morning and python, pip, the databricks cli and the repo were all freshly installed \ cloned as of this morning.

I have checked that the Databricks CLI can list resources successfully within the workspace, such as cluster and notebooks.

The command I am running is:

`python3 migration_pipeline.py --profile oldWS --export-pipeline --use-checkpoint --session RT20230314 --azure --skip-tasks instance_profiles users groups secrets clusters instance_pools jobs `

However, this is returning the error:

`Traceback (most recent call last):
  File "migration_pipeline.py", line 349, in <module>
    main()
  File "migration_pipeline.py", line 345, in main
    pipeline.run()
  File "/home/devops-admin/migrate/pipeline/pipeline.py", line 64, in run
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/devops-admin/migrate/pipeline/pipeline.py", line 73, in _run_task
    task.run()
  File "/home/devops-admin/migrate/tasks/tasks.py", line 110, in run
    num_notebooks = ws_c.log_all_workspace_items_entry(exclude_prefixes=self.args.exclude_work_item_prefixes)
  File "/home/devops-admin/migrate/dbclient/WorkspaceClient.py", line 412, in log_all_workspace_items_entry
    num_nbs = self.log_all_workspace_items(ws_path=ws_path,
  File "/home/devops-admin/migrate/dbclient/WorkspaceClient.py", line 445, in log_all_workspace_items
    items = self.get(WS_LIST, get_args).get('objects', None)
  File "/home/devops-admin/migrate/dbclient/dbclient.py", line 205, in get
    raw_results = self.req_session().get(
  File "/home/devops-admin/migrate/dbclient/dbclient.py", line 184, in req_session
    adapter = HTTPAdapter(max_retries=Retry(
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'`

**Comment by TylrRssll** [comment]
Hello, I have version 1.26.15 currently installed which according to this https://pypi.org/project/urllib3/ is the latest stable version.

**Comment by TylrRssll** [comment]
@gregwood-db any other suggestions?

**Comment by gregwood-db** [comment]
@TylrRssll does running the following in a python terminal also cause an error? I tried this with an older version of urllib3 (1.26.8) and also the latest version (1.26.15) and both worked alright. Feel free to also post your environment details.

```
from requests.adapters import HTTPAdapter
from requests.packages.urllib3 import Retry

http_retry_codes = [429, 503, 504]

adapter = HTTPAdapter(max_retries=Retry(total=5,
backoff_factor=1,
status_forcelist=http_retry_codes,
allowed_methods=frozenset({'DELETE', 'GET', 'HEAD', 'OPTIONS', 'PATCH', 'POST', 'PUT', 'TRACE' }),
raise_on_status=False))
```

**Comment by TylrRssll** [comment]
@gregwood-db I was getting the same error when running in a terminal:

`TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
`
Even though pip freeze was showing the correct version of urllib3, I decided to uninstall the dependency and re-install, and that has now solved the issue.  

Thank you for getting back to me.

**Comment by TylrRssll** [comment]
@gregwood-db I was getting the same error when running in a terminal:

`TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
`
Even though pip freeze was showing the correct version of urllib3, I decided to uninstall the dependency and re-install, and that has now solved the issue.  

Thank you for getting back to me.
