### ISSUE TITLE
Does this tool perform any destructive changes?

### ISSUE THREAD

**Issue by polynomialherder** [databrickslabs/migrate#271]
Will running this tool against my workspace destroy any existing AWS/Azure/GCP resources associated with the original workspace, or does it clone the resources and duplicate the configuration of the original workspace in the target cloud environment without performing any modifications to the original workspace cloud environment?

It wasn't clear to me from reading the documentation whether this tool performed destructive changes -- apologies if I missed it

**Comment by mrchristine** [comment]
This tool will not destroy any cloud resources for workspaces. It only deals with workspace artifacts.

**Comment by polynomialherder** [comment]
@mrchristine does this destroy any workspace artifacts -- anything at all inside the databricks workspace? Can it be run more than once for testing purposes or to validate the process before performing a live migration?
