### ISSUE TITLE
Add --skip-failed option to Notebook export

### ISSUE THREAD

**Issue by a-terado** [databrickslabs/migrate#272]
When customers export notebooks beyond a specific size (~80MB) they get the following error `{"error_code": "BAD_REQUEST", "message": "Size exceeds 10485760 bytes", "http_status_code": 400, "path": "/Users/xxx@xxx.com/xxx"}` There is no way to skip the failed notebooks right now, and the only workaround is to manually clear the outputs of the large notebooks. This is difficult when there are multiple different teams of users and 100s of notebooks.

Adding a --skip-failed option will help customers execute on the migration while allowing them to skip the large notebooks.

**Comment by gregwood-db** [comment]
@a-terado Try out the `--skip-large-nb` flag added in bae47236effcfdd56c55f37d241f94ff4bff9c74 and re-open this issue if the commit does not solve the ask.
