### ISSUE TITLE
secrets scopes become inaccessible for users when the migration targets an E2 account below of Premium 

### ISSUE THREAD

**Issue by davidvega-db** [databrickslabs/migrate#284]
When migrating from Legacy Workspace to E2 account below from Premium, the secrets scopes become inaccessible for the general users since these accounts do not have ACL enabled which is a problem when there are too many scopes.

It is required to adjust the script for these account have allowed to concat or enable "--initial-manage-principal users" while doing the migration (link reference: https://docs.databricks.com/en/security/secrets/secret-scopes.html#create-a-databricks-backed-secret-scope)

**Comment by davidvega-db** [comment]
NOTE: When I mean become inacessible, it is because of this message:
PERMISSION_DENIED: User <email-account> does not have READ permission on scope <scope-name> to perform this action.

**Comment by gregwood-db** [comment]
@davidvega-db can you have the customer try the hotfix branch to see if the `bypass-secret-acl` option fixes this issue?

**Comment by davidvega-db** [comment]
@gregwood-db case was closed due to a lack of response from the customer. I will let you know any update in case they provide any feedback about that option
