### ISSUE TITLE
Can this tool handle migration from a normal E2 workspace to Unity Catalogue  

### ISSUE THREAD

**Issue by Debanjoy** [databrickslabs/migrate#285]
Hey 
Was curious on will this Migration tool be able to Handel migration between E2 workspace to a Unity catalogue workspace is there a best practice I am in dire need with suggestions. Please advice.

**Comment by gregwood-db** [comment]
@Debanjoy this is not a planned functionality. The [Terraform Exporter](https://registry.terraform.io/providers/databricks/databricks/latest/docs/guides/experimental-exporter) is probably a better solution for UC workspaces.
