### ISSUE TITLE
Does this tool destroy workspace artifacts?

### ISSUE THREAD

**Issue by polynomialherder** [databrickslabs/migrate#290]
Does this tool destroy Databricks resources (compute, notebooks, tables -- anything at all)? 

In particular, if I am testing this tool on an existing workspace, can I run it more than once on the same source workspace but possibly different targets for testing and validation purposes and expect to see the same results, or will it perform destructive changes to the source that might yield different results on different invocations, even with the same configuration?

**Comment by mrchristine** [comment]
No, it doesn't destroy anything UNLESS you provide an option to do so. If you look at the import help text and read all the options, one such option exists in case you need to test imports for job templates. 

```  --delete-all-jobs     Delete all jobs ```

Exports are safe to re-run continuously, imports are also safe unless you pass an option to clean stuff up. If you import and the artifact exists, it will be skipped.

**Comment by polynomialherder** [comment]
@mrchristine Got it -- thank you!

**Comment by polynomialherder** [comment]
@mrchristine Got it -- thank you!
