### ISSUE TITLE
Migrated internal tables are empty.

### ISSUE THREAD

**Issue by johnlourdu** [databrickslabs/migrate#300]
When I try to import/export metastore and metastore-acl, empty tables are created on the destination workspace. Is this expected? If so, what is the ideal solution to migrate the internal tables over to a new workspace. I am aware of UC but we're yet to migrate to UC.

**Comment by mrchristine** [comment]
This is expected behavior. @johnlourdu the data is stored in a customers storage account, they will need to use native cloud tools to copy over the data from `dbfs:/user/hive/warehouse`.
