### ISSUE TITLE
Issue with running migration script, getting login with credentials error but entered right tokens

### ISSUE THREAD

**Issue by jayasimhamadhira** [databrickslabs/migrate#302]
![Capture](https://github.com/user-attachments/assets/2340435b-766d-4af6-a58c-c00d9533e3f0)

Attached the error while running the migration script.

**Comment by mrchristine** [comment]
The error indicates that you don't have the `oldWS` profile defined in the configuration file and it isn't able to find the profile. Given that others have not reported this, I'd recommend reviewing your configuration files and setup.
