### ISSUE TITLE
No set up documentation or step by step guide is provided.

### ISSUE THREAD

**Issue by AlphaAnalyticsAUS** [databrickslabs/migrate#31]
I can not find proper set up instructions for this package to install on Ubuntu and set up databricks configuration to connect to workspace and run commands. Examples are documented in limited sense.

**Comment by mrchristine** [comment]
The credentials are configured with the Databricks CLI package. 
https://docs.databricks.com/dev-tools/cli/index.html

It is noted within the README: 
```This package uses credentials from the Databricks CLI```
