### ISSUE TITLE
RE is missing on HiveClient

### ISSUE THREAD

**Issue by andre-sasaki** [databrickslabs/migrate#41]
RE is not being imported on dbclient/HiveClient but it's being used in line 47. https://github.com/databrickslabs/migrate/blob/31d3f322c062d39ee1cfc1c276e3f03ae2ac7288/dbclient/HiveClient.py#L47

**Comment by andre-sasaki** [comment]
https://github.com/databrickslabs/migrate/pull/42

**Comment by afsana-afzal** [comment]
@mrchristine
