### ISSUE TITLE
Group membership for users is not imported

### ISSUE THREAD

**Issue by lotnikov** [databrickslabs/migrate#44]
Groups are created while import of ./groups folder (ScimClient.py - import_groups) using iteration over groups = self.listdir(group_dir), here "groups" is a generator object
But then there is another iteration over the same generator "group", which should import group membership for users. But generator has already iterated over all files in ./groups folder, so no iteration happens, so no group membership for users is impported.
I just reinitalized a generator before next iteration and it worked for me:
![Screenshot 2021-07-29 142940](https://user-images.githubusercontent.com/18272061/127484552-9a08d7d7-4cbf-48b4-90f1-54900e875830.jpg)

**Comment by mrchristine** [comment]
Thanks for catching this. A fix for another bug caused this regression due to changing the behavior of listdir() to be a generator.
