### ISSUE TITLE
Import metastore - NameError: name 're' is not defined

### ISSUE THREAD

**Issue by lotnikov** [databrickslabs/migrate#45]
Looks like it is needed to add "import re" to HiveClient.py

  File "/home/hadoop/databricks/migrate/dbclient/HiveClient.py", line 48, in get_path_option_if_available
    params = re.search(r'\((.*?)\)', stmt).group(1)
NameError: name 're' is not defined

**Comment by mrchristine** [comment]
@lotnikov this was resolved recently w/ https://github.com/databrickslabs/migrate/issues/41
