### ISSUE TITLE
Support workspace-acls for single user export.

### ISSUE THREAD

**Issue by rohitnijhawan** [databrickslabs/migrate#52]
When a user executes a command like this.
`python export_db.py --profile demo --azure --export-home me.user@databricks.com --workspace-acls`

It throws the error below. When the workspace-acls option is not used, no ACLs are exported.
```
Traceback (most recent call last):
  File "export_db.py", line 297, in <module>
    main()
  File "export_db.py", line 72, in main
    ws_c.log_all_workspace_acls()
  File "/databricks/driver/git1/migrate/build/lib/dbclient/WorkspaceClient.py", line 388, in log_all_workspace_acls
    self.log_acl_to_file('notebooks', workspace_log_file, 'acl_notebooks.log', 'failed_acl_notebooks.log')
  File "/databricks/driver/git1/migrate/build/lib/dbclient/WorkspaceClient.py", line 364, in log_acl_to_file
    with open(read_log_path, 'r') as read_fp, open(write_log_path, 'w') as write_fp, \
FileNotFoundError: [Errno 2] No such file or directory: 'azure_logs/user_workspace.log'
```

**Comment by mrchristine** [comment]
It throws an error as it's not yet supported. Will tag this as a feature request. 
See `Single User Export/Import` in the README for supported options.

**Comment by mrchristine** [comment]
@rohitnijhawan I added this functionality in the existing parameters of `--export-home` and `--import-home` to include ACLs. Please try again w/ the latest commit and remove the additional `--workspace-acls` parameter.
