### ISSUE TITLE
Support migration of multi task jobs

### ISSUE THREAD

**Issue by terrymunro** [databrickslabs/migrate#60]
While doing the Jobs import (`python export_db.py --profile DEMO --jobs` -> `python import_db.py --profile NEW-DEMO --jobs`) I ran into:

```
Traceback (most recent call last):
  File "import_db.py", line 219, in <module>
    main()
  File "import_db.py", line 105, in main
    jobs_c.import_job_configs()
  File "/home/terry/databricks/migrate/dbclient/JobsClient.py", line 110, in import_job_configs
    cluster_conf = job_settings['new_cluster']
KeyError: 'new_cluster'
```

[Looking at the code](https://github.com/databrickslabs/migrate/blob/master/dbclient/JobsClient.py#L110), it seems that it parses the JSON from the `jobs.log` file and expects there to be a `'new_cluster'` key, which for MULTI_TASK may not be the case.

For reference, here's what my multi-task job's JSON looked like:
```json
  {
    "job_id": 1234,
    "settings": {
      "name": "Example:::1234",
      "email_notifications": {
        "on_failure": ["terry.munro@literacyplanet.com"],
        "no_alert_for_skipped_runs": true
      },
      "timeout_seconds": 0,
      "schedule": {
        "quartz_cron_expression": "51 30 23 * * ?",
        "timezone_id": "Australia/Brisbane",
        "pause_status": "UNPAUSED"
      },
      "max_concurrent_runs": 1,
      "format": "MULTI_TASK"
    },
    "created_time": 1628241879369,
    "creator_user_name": "terry.munro@literacyplanet.com"
  }
 ```

**Comment by terrymunro** [comment]
Right, I didn't check there was already a [pull request](https://github.com/databrickslabs/migrate/pull/58) for it

**Comment by mrchristine** [comment]
Yes, closing this out as a duplicate. #58 is in testing right now. Feel free to give the PR a test and report your findings.
