### ISSUE TITLE
Parallelize API calls

### ISSUE THREAD

**Issue by kmate** [databrickslabs/migrate#89]
Hi!

I used this tool recently to migrate some larger user homes with nearly a thousand notebooks. I noticed that the whole download/upload part is singe-threaded as the rest of the application. This makes the process very slow, for me it took more than an hour to download a single user home, compared to a few (<6) minutes when I parallelized the download part. It was something like this:

```python
from joblib import Parallel, delayed
...
def download_notebooks(self, ws_log_file='user_workspace.log', ws_dir='artifacts/'):
    ...
            responses = Parallel(n_jobs=16)(delayed(self.download_notebook_helper)(nd, self.get_export_dir() + ws_dir) for nd in fp)
            for dl_resp in responses:
                if 'error_code' not in dl_resp:
                    num_notebooks += 1

# param notebook_path changed to notebook_data
def download_notebook_helper(self, notebook_data, export_dir='artifacts/'):
    ...
    # moved from the original invocation in download_notebooks
    notebook_path = json.loads(notebook_data).get('path', None).rstrip('\n')
    ...
```

This could be done in multiple places where a lot of API requests are issued. Some of these are a bit harder to parallelize as they're recursive (like `log_all_workspace_items`), but that's also not impossible I think.

I'm not a python professional or neither someone who fully understands all parts of the tool now so I cannot really open a meaningful PR from this, but I'd be very happy if such improvements could be done.

Thanks!

**Comment by alexott** [comment]
Main challenge is obeying the rate limits

**Comment by mrchristine** [comment]
Thanks for filing this @kmate . As Alex pointed out there are some challenges with this in terms of rate limits within Databricks to prevent DDOS attacks against the rest api server. We are looking at ways to improve the overall performance of this tooling in general, and will keep this in mind to focus on notebook performance.

**Comment by kmate** [comment]
I think if we could queue the requests to be parallelized somehow then it'd be easy to obey a pre-set rate limit (I'm not sure how hard it is to implement such architecture in python, especially). However with the above parallelism I didn't have such problem when scraping a few thousand notebooks from a single workspace, I got no "slow down" responses or similar.

**Comment by kevinkim9264** [comment]
@kmate could you also tell me which other steps took long?

**Comment by kevinkim9264** [comment]
Working on it via: https://github.com/databrickslabs/migrate/pull/103

**Comment by gregwood-db** [comment]
Closing since this was merged.
